//! The game's content, as `public/data/game.json` holds it.
//!
//! The file is generated by `love2d/tools/dump_web.lua` and is the LÖVE data
//! unchanged: `src/quests.lua`, the twenty `src/data*.lua` chips and the
//! string table of `src/i18n.lua`, encoded rather than rewritten. A translated
//! field is still the `{ en =, ko =, yue = }` table the desktop game reads, so
//! a line added to a Lua file reaches the web build with no second edit.

use serde::Deserialize;
use std::collections::HashMap;

/// One translated string. English is always there; the other two are written
/// inline in the Lua sources, and the languages added later are looked up by
/// their English text in [`Doc::tr`].
#[derive(Debug, Clone, Deserialize, Default)]
pub struct Loc {
    pub en: String,
    #[serde(default)]
    pub ko: Option<String>,
    #[serde(default)]
    pub yue: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Track {
    pub id: String,
    pub label: String,
    pub item: String,
    /// The fence tag a Markdown export puts on this track's code.
    pub lang: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Win {
    pub stamp: String,
    pub bg: String,
    pub title: String,
    pub head: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Npc {
    pub kind: String,
    pub x: f32,
    #[serde(default = "one")]
    pub facing: f32,
    pub line: Loc,
}

fn one() -> f32 {
    1.0
}

/// One blank: a question, a code block with `___` in it, and what counts as
/// the answer. `accept` is the full list; `answer` is the one that is shown.
#[derive(Debug, Clone, Deserialize)]
pub struct Stage {
    pub topic: String,
    pub q: Loc,
    pub code: Loc,
    pub accept: Vec<String>,
    #[serde(default)]
    pub answer: Option<String>,
    pub hint: Loc,
    pub ok: Loc,
}

impl Stage {
    /// What the blank fills in with once the street is CLEAR: the written
    /// answer, or the first thing the street would have accepted.
    pub fn shown_answer(&self) -> &str {
        self.answer
            .as_deref()
            .or_else(|| self.accept.first().map(String::as_str))
            .unwrap_or("")
    }
}

/// One street. `viz` names the little animated scene drawn behind the people;
/// the tracks added after Go describe theirs as `chips` and a `note` instead
/// of getting a hand-drawn one.
#[derive(Debug, Clone, Deserialize)]
pub struct MapDef {
    pub id: String,
    pub station: String,
    pub name: Loc,
    pub title: Loc,
    pub lesson: Loc,
    pub bg: String,
    pub portrait: String,
    pub speaker: Loc,
    pub ground: f32,
    pub spawn: f32,
    pub width: f32,
    #[serde(default)]
    pub npcs: Vec<Npc>,
    pub viz: String,
    pub story: Loc,
    pub stages: Vec<Stage>,
    /// `[[text, colour], ...]` for the generic scene.
    #[serde(default)]
    pub chips: Vec<(String, String)>,
    #[serde(default)]
    pub note: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Quest {
    pub id: String,
    pub track: String,
    pub tag: String,
    pub station: String,
    pub name: Loc,
    pub goal: Loc,
    pub win: Win,
    pub maps: Vec<MapDef>,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Doc {
    pub langs: Vec<String>,
    pub lang_names: HashMap<String, String>,
    pub strings: HashMap<String, Loc>,
    /// By-English translation tables, one per language that has a
    /// `src/lang/<code>.lua`.
    pub tr: HashMap<String, HashMap<String, String>>,
    pub tracks: Vec<Track>,
    pub quests: Vec<Quest>,
}

impl Doc {
    pub fn parse(json: &str) -> Result<Doc, String> {
        let doc: Doc = serde_json::from_str(json).map_err(|e| format!("game.json: {e}"))?;
        doc.check()?;
        Ok(doc)
    }

    /// The invariants the rest of the crate indexes on without asking.
    ///
    /// A document that parses is not yet a game: an empty `tracks` or a quest
    /// with no streets would take the first draw down with an index panic, and
    /// a panic in wasm is a dead page with nothing on it. Refusing here means
    /// the shell shows "the questions did not load", which at least says what
    /// went wrong.
    fn check(&self) -> Result<(), String> {
        if self.tracks.is_empty() {
            return Err("game.json: no tracks".into());
        }
        if self.quests.is_empty() {
            return Err("game.json: no quests".into());
        }
        for q in &self.quests {
            if q.maps.is_empty() {
                return Err(format!("game.json: quest {} has no streets", q.tag));
            }
            for m in &q.maps {
                if m.stages.is_empty() {
                    return Err(format!("game.json: street {} has no blanks", m.id));
                }
            }
        }
        Ok(())
    }

    pub fn track_def(&self, id: &str) -> &Track {
        self.tracks
            .iter()
            .find(|t| t.id == id)
            .unwrap_or(&self.tracks[0])
    }

    /// Flat quest indices of one track, in tab order. Quests are appended and
    /// never inserted, so a saved quest number keeps meaning what it meant.
    pub fn of_track(&self, track: &str) -> Vec<usize> {
        (0..self.quests.len())
            .filter(|&q| self.quests[q].track == track)
            .collect()
    }

    pub fn first_of(&self, track: &str) -> usize {
        self.of_track(track).first().copied().unwrap_or(0)
    }

    /// 0-based position of quest `q` inside its own track.
    pub fn index_in_track(&self, q: usize) -> usize {
        let Some(quest) = self.quests.get(q) else {
            return 0;
        };
        self.of_track(&quest.track)
            .iter()
            .position(|&i| i == q)
            .unwrap_or(0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_document_that_parses_but_cannot_be_played_is_refused() {
        // Every one of these would otherwise panic on the first draw, and a
        // panic in wasm is a blank page rather than a message.
        let base = r#"{"langs":[],"langNames":{},"strings":{},"tr":{},"#;
        for (tail, why) in [
            (r#""tracks":[],"quests":[]}"#, "no tracks"),
            (
                r#""tracks":[{"id":"go","label":"GO","item":"i","lang":"go"}],"quests":[]}"#,
                "no quests",
            ),
        ] {
            let err = Doc::parse(&format!("{base}{tail}")).unwrap_err();
            assert!(err.contains(why), "{err:?} should mention {why:?}");
        }
        assert!(Doc::parse("not json").is_err());
    }

    #[test]
    fn a_stage_falls_back_to_the_first_accepted_answer() {
        let st = Stage {
            topic: "PACKAGE".into(),
            q: Loc::default(),
            code: Loc::default(),
            accept: vec!["main".into()],
            answer: None,
            hint: Loc::default(),
            ok: Loc::default(),
        };
        assert_eq!(st.shown_answer(), "main");
    }
}
